[package]
name = "shelf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["full"]}
redis = { version = "0.21.5", features = ["tokio-comp"] }
clap = { version = "3.1.6", features = ["derive"] }
bytes = "1.1.0"
thiserror = "1.0"
atoi = "1.0.0"
